# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["core.py"]

doc_url = "https://cfgarciar.github.io/test_nbdev/"

git_url = "https://github.com/cfgarciar/test_nbdev/tree/master/"

def custom_doc_links(name): return None
